/**
 * 🏢 Site Data — Central Configuration
 *
 * All repetitive brand details, contact info, links, and metadata live here.
 * Import these values instead of hardcoding strings across the codebase.
 * This keeps renaming and rebranding to a single file change.
 */

// ─── Brand ────────────────────────────────────────────────────────────────

export const APP_NAME = "Prism";
export const APP_SHORT_NAME = "Prism";
export const APP_TAGLINE = "Multi-Tenant Platform";
export const APP_DESCRIPTION = "Comprehensive school management system";

/** Used for meta titles — e.g. "Upgrade Required — Prism" */
export const APP_TITLE_SUFFIX = `— ${APP_NAME}`;

// ─── Company / Contact ───────────────────────────────────────────────────

export const CONTACT_EMAIL = "hello@prism.app";
export const SUPPORT_EMAIL = "support@prism.app";
export const DPO_EMAIL = "dpo@prism.app";
export const CONTACT_PHONE = "+1 (555) 123-4567";
export const COMPANY_ADDRESS = {
  line1: "123 Education Ave, Suite 200",
  city: "San Francisco",
  state: "CA",
  zip: "94105",
  country: "USA",
  full: "123 Education Ave, Suite 200\nSan Francisco, CA 94105",
};

// ─── Branding / Theme ────────────────────────────────────────────────────

export const BRAND_COLORS = {
  primary: "#2563eb",       // blue-600
  primaryDark: "#1d4ed8",   // blue-700
  secondary: "#059669",     // emerald-600
  accent: "#7c3aed",       // violet-600
} as const;

export const BRAND_GRADIENT = "from-blue-600 to-indigo-600" as const;

// ─── SEO / Metadata ──────────────────────────────────────────────────────

export const SITE_URL = "https://prism.app";
export const SITE_KEYWORDS = [
  "school management",
  "multi-tenant",
  "education platform",
  "school administration",
  "learning management",
];

// ─── Gradients ──────────────────────────────────────────────────────────

export const GRADIENTS = {
  brand: "from-blue-600 via-blue-500 to-indigo-500",
  hero: "from-blue-600 via-indigo-600 to-purple-700",
  cta: "from-blue-600 to-indigo-600",
} as const;

// ─── Email Signatures ─────────────────────────────────────────────────────

export const EMAIL_SENDER_TEAM = "— The Prism Team";
export const EMAIL_SENDER_SYSTEM = "— Prism System";

// ─── Generated Document Footers ───────────────────────────────────────────

export const DOC_FOOTER_LESSON_NOTES = "Generated by Prism AI Lesson Notes";
export const DOC_FOOTER_LESSON_NOTES_EXPORT = "Generated by Prism Lesson Notes";

// ─── Footer / Legal ──────────────────────────────────────────────────────

export const COPYRIGHT_START_YEAR = 2024;
export const COPYRIGHT_HOLDER = APP_NAME;

export function getCopyrightText(): string {
  const year = COPYRIGHT_START_YEAR < new Date().getFullYear()
    ? `${COPYRIGHT_START_YEAR}–${new Date().getFullYear()}`
    : `${COPYRIGHT_START_YEAR}`;
  return `© ${year} ${COPYRIGHT_HOLDER}. All rights reserved.`;
}

// ─── Email ────────────────────────────────────────────────────────────────

/**
 * Default sender name used in transactional emails.
 * Also imported by lib/school-branding.ts as a fallback.
 */
export const PLATFORM_NAME = APP_NAME;
export const DEFAULT_FROM_EMAIL = "noreply@mail.prism.app";

// ─── Landing Page ─────────────────────────────────────────────────────────

export const HERO_HEADLINE = "One Platform to Manage Every School in Your Network";
export const HERO_SUBHEADLINE =
  "A powerful, multi-tenant school management system designed for school groups, districts, and education organizations. Manage academics, operations, finance, and communications from a single unified dashboard.";

export const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "Pricing", href: "/subscription" },
  { label: "Portals", href: "#portals" },
] as const;

export const STATS = [
  { end: 10000, suffix: "+", label: "Students Managed" },
  { end: 500, suffix: "+", label: "Schools Onboarded" },
  { end: 50000, suffix: "+", label: "Reports Generated" },
  { end: 99.9, suffix: "%", label: "Platform Uptime" },
] as const;

export const PORTALS = [
  {
    role: "Admin",
    href: "/admin/login",
    description:
      "Full administrative control — manage users, configure academic structure, oversee operations, and generate institutional reports.",
    stats: ["School Config", "Staff Management", "Finance", "Analytics"],
    gradient: "from-slate-900 to-slate-700",
  },
  {
    role: "Teacher",
    href: "/teacher/login",
    description:
      "Manage classes, record assessments, track attendance, communicate with parents, and monitor student progress daily.",
    stats: ["Gradebook", "Attendance", "Lesson Plans", "Analytics"],
    gradient: "from-blue-700 to-blue-500",
  },
  {
    role: "Student",
    href: "/student/login",
    description:
      "View grades, check timetables, track attendance records, access learning materials, and receive school announcements.",
    stats: ["Results", "Timetable", "Assignments", "Progress"],
    gradient: "from-emerald-700 to-emerald-500",
  },
  {
    role: "Parent",
    href: "/parent/login",
    description:
      "Stay connected with your child's academic journey — monitor performance, attendance, fee status, and school communications.",
    stats: ["Performance", "Attendance", "Payments", "Messages"],
    gradient: "from-amber-700 to-amber-500",
  },
] as const;

// ─── Footer Links ─────────────────────────────────────────────────────────

export const FOOTER_LINKS = {
  product: [
    { label: "Features", href: "#features" },
    { label: "Pricing", href: "/subscription" },
    { label: "Register your school", href: "/register" },
    { label: "Integrations", href: "#" },
    { label: "API Docs", href: "#" },
  ],
  company: [
    { label: "About", href: "#" },
    { label: "Blog", href: "#" },
    { label: "Careers", href: "#" },
    { label: "Press Kit", href: "#" },
    { label: "Partners", href: "#" },
  ],
} as const;
