/**
 * Query Executor
 * Safely executes SQL queries generated by the AI Query Planner
 */

import { createClient } from '@supabase/supabase-js';
import type { QueryPlan } from './query-planner';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

export interface QueryResult {
  success: boolean;
  data?: any[];
  error?: string;
  rowCount?: number;
}

/**
 * Execute a query plan with proper school_id and user context
 */
export async function executeQueryPlan(
  queryPlan: QueryPlan,
  schoolId: string,
  userId?: string
): Promise<QueryResult> {
  try {
    // Validate query
    if (queryPlan.error) {
      return {
        success: false,
        error: queryPlan.error
      };
    }

    if (!queryPlan.query) {
      return {
        success: false,
        error: 'No query provided'
      };
    }

    // Replace placeholder values with actual values
    let finalQuery = queryPlan.query;
    queryPlan.values.forEach((val, index) => {
      let replacementValue = val;
      if (val === '<school_id>') {
        replacementValue = schoolId;
      } else if (val === '<user_id>') {
        replacementValue = userId;
      }

      // Escape values for SQL
      const escapedValue = typeof replacementValue === 'string' 
        ? `'${replacementValue.replace(/'/g, "''")}'` 
        : replacementValue;

      // Replace $1, $2, etc. with actual values
      const placeholder = `$${index + 1}`;
      finalQuery = finalQuery.replace(new RegExp(`\\${placeholder}`, 'g'), String(escapedValue));
    });

    // Create Supabase client with service role
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Execute query using the RPC function without parameters
    const { data, error } = await supabase.rpc('execute_ai_query', {
      p_query: finalQuery
    });

    if (error) {
      console.error('Query execution error:', error);
      return {
        success: false,
        error: error.message || 'Query execution failed'
      };
    }

    // Parse results - handle both RECORD and JSON formats
    let parsedData = data || [];
    if (Array.isArray(parsedData) && parsedData.length > 0) {
      // If results are wrapped in 'result' key, unwrap them
      if (parsedData[0]?.result) {
        parsedData = parsedData.map(item => {
          if (typeof item.result === 'string') {
            try {
              return JSON.parse(item.result);
            } catch {
              return item.result;
            }
          }
          return item.result;
        });
      }
    }

    return {
      success: true,
      data: parsedData,
      rowCount: parsedData?.length || 0
    };
  } catch (error) {
    console.error('Error executing query:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Execute a raw parameterized query (for testing/debugging)
 * Only available in development mode
 */
export async function executeRawQuery(
  query: string,
  values: any[],
  schoolId: string
): Promise<QueryResult> {
  if (process.env.NODE_ENV === 'production') {
    return {
      success: false,
      error: 'Raw queries not allowed in production'
    };
  }

  try {
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { data, error } = await supabase.rpc('execute_ai_query', {
      query_text: query,
      query_params: [schoolId, ...values]
    });

    if (error) {
      return {
        success: false,
        error: error.message
      };
    }

    return {
      success: true,
      data: data || [],
      rowCount: data?.length || 0
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
