/**
 * Query Executor
 * Safely executes SQL queries generated by the AI Query Planner
 * Uses client auth with RLS to prevent unauthorized database access
 */

import { createBrowserClient } from '@supabase/ssr';
import type { QueryPlan } from './query-planner';

export interface QueryResult {
  success: boolean;
  data?: any[];
  error?: string;
  errorCode?: string;
  errorDetails?: string | null;
  errorHint?: string | null;
  rowCount?: number;
}

/**
 * Execute a query plan with proper school_id and user context using RLS
 */
export async function executeQueryPlan(
  queryPlan: QueryPlan,
  schoolId: string,
  userId?: string
): Promise<QueryResult> {
  try {
    // Validate schoolId is provided and is a valid UUID
    if (!schoolId || schoolId.trim() === '') {
      return {
        success: false,
        error: 'School ID is required for query execution'
      };
    }

    if (schoolId === '<school_id>') {
      return {
        success: false,
        error: 'School ID placeholder not replaced. Please provide actual school_id'
      };
    }

    // Validate query
    if (queryPlan.error) {
      return {
        success: false,
        error: queryPlan.error
      };
    }

    if (!queryPlan.query) {
      return {
        success: false,
        error: 'No query provided'
      };
    }

    // Replace placeholder values with actual values
    let finalQuery = queryPlan.query;
    
    // First, ensure school_id and user_id are replaced in the query (these might be in the query string but not in values array)
    if (finalQuery.includes('<school_id>')) {
      if (!schoolId) {
        return {
          success: false,
          error: 'School ID is required but not provided. Cannot execute query.'
        };
      }
      // Replace all occurrences of <school_id> placeholder.
      // Handle cases where the AI may include surrounding quotes around the token
      // (e.g. "'<school_id>'") to avoid producing double-quoted literals.
      const escapedSchoolId = `'${schoolId.replace(/'/g, "''")}'`;
      finalQuery = finalQuery.replace(/'?<school_id>'?/g, escapedSchoolId);
    }
    
    if (finalQuery.includes('<user_id>')) {
      if (!userId) {
        return {
          success: false,
          error: 'User ID is required but not provided. Cannot execute query.'
        };
      }
      // Replace all occurrences of <user_id> placeholder.
      // Handle optional surrounding quotes to avoid double-quoting.
      const escapedUserId = `'${userId.replace(/'/g, "''")}'`;
      finalQuery = finalQuery.replace(/'?<user_id>'?/g, escapedUserId);
    }
    
    // Then process the values array for parameterized placeholders ($1, $2, etc.)
    const values = Array.isArray(queryPlan.values) ? queryPlan.values : [];
    let missingUserId = false;
    values.forEach((val, index) => {
      let replacementValue = val;

      if (val === '<school_id>') {
        replacementValue = schoolId;
      } else if (val === '<user_id>') {
        if (!userId) {
          missingUserId = true;
          return;
        }
        replacementValue = userId;
      }

      // Escape values for SQL
      const escapedValue = typeof replacementValue === 'string'
        ? `'${replacementValue.replace(/'/g, "''")}'`
        : replacementValue;

      // Replace $1, $2, etc. with actual values
      const placeholder = `$${index + 1}`;
      finalQuery = finalQuery.replace(new RegExp(`\\${placeholder}`, 'g'), String(escapedValue));
    });

    if (missingUserId) {
      return {
        success: false,
        error: 'User ID is required but not provided. Cannot execute query.'
      };
    }

    // Create Supabase client with user authentication (RLS enforced)
    const supabase = createBrowserClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    // Verify all placeholders were replaced
    if (finalQuery.includes('<school_id>') || finalQuery.includes('<user_id>')) {
      return {
        success: false,
        error: 'Query contains unreplaced placeholders. School ID or User ID not provided.'
      };
    }

    // If any positional parameter placeholders remain ($1, $2...), abort to avoid accidental execution
    if (/\$[1-9][0-9]*/.test(finalQuery)) {
      return {
        success: false,
        error: 'Query contains unreplaced positional parameter placeholders (e.g. $1). Please provide matching values in the query plan.'
      };
    }

    // Execute query using the RPC function with user's authenticated session
    // RLS policies will be enforced automatically
    const { data, error } = await supabase.rpc('execute_ai_query', {
      p_query: finalQuery
    });

    if (error) {
      console.error('Query execution error:', error);
      return {
        success: false,
        error: error.message || 'Query execution failed',
        errorCode: error.code,
        errorDetails: error.details,
        errorHint: error.hint
      };
    }

    // Parse results - handle both RECORD and JSON formats
    let parsedData = data || [];
    if (Array.isArray(parsedData) && parsedData.length > 0) {
      // If results are wrapped in 'result' key, unwrap them
      if (parsedData[0]?.result) {
        parsedData = parsedData.map(item => {
          if (typeof item.result === 'string') {
            try {
              return JSON.parse(item.result);
            } catch {
              return item.result;
            }
          }
          return item.result;
        });
      }
    }

    return {
      success: true,
      data: parsedData,
      rowCount: parsedData?.length || 0
    };
  } catch (error) {
    console.error('Error executing query:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}

/**
 * Execute a raw parameterized query (for testing/debugging)
 * Only available in development mode, uses RLS for security
 */
export async function executeRawQuery(
  query: string,
  values: any[],
  schoolId: string
): Promise<QueryResult> {
  if (process.env.NODE_ENV === 'production') {
    return {
      success: false,
      error: 'Raw queries not allowed in production'
    };
  }

  try {
    const supabase = createBrowserClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    const { data, error } = await supabase.rpc('execute_ai_query', {
      query_text: query,
      query_params: [schoolId, ...values]
    });

    if (error) {
      return {
        success: false,
        error: error.message
      };
    }

    return {
      success: true,
      data: data || [],
      rowCount: data?.length || 0
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
